### ISSUE TITLE
[功能建议] 预处理会将谱面删除

### ISSUE THREAD

**Issue by Becods** [RightSG/open-mdp#4]
https://github.com/RightSG/open-mdp/blob/289089a53bb53ffedefd1402048cf15f7d0a4679/serializer/src/Program.cs#L109-L118

如果第一次用不清楚的情况下可能就中招了(虽然说编辑器打开过的基本都有maidata.bak.txt可以恢复)

**Comment by RightSG** [comment]
这个实际上是Program.cs里的内容和exe对不上导致的，直接用exe的话不会出现直接介入文件删除和凭空要求temp文件夹的情况，我回头重写一下Program.cs
